//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlGeneratorServices.SinosoftWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBase64Binary", Namespace="http://service.webservice.sinosoft.com", ItemName="base64Binary")]
    [System.SerializableAttribute()]
    public class ArrayOfBase64Binary : System.Collections.Generic.List<byte[]> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.webservice.sinosoft.com", ConfigurationName="SinosoftWS.MPOSServicePortType")]
    public interface MPOSServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string _SPAJToCore(string in0, HtmlGeneratorServices.SinosoftWS.ArrayOfBase64Binary in1, HtmlGeneratorServices.SinosoftWS.ArrayOfBase64Binary in2, HtmlGeneratorServices.SinosoftWS.ArrayOfBase64Binary in3, HtmlGeneratorServices.SinosoftWS.ArrayOfBase64Binary in4);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MPOSServicePortTypeChannel : HtmlGeneratorServices.SinosoftWS.MPOSServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MPOSServicePortTypeClient : System.ServiceModel.ClientBase<HtmlGeneratorServices.SinosoftWS.MPOSServicePortType>, HtmlGeneratorServices.SinosoftWS.MPOSServicePortType {
        
        public MPOSServicePortTypeClient() {
        }
        
        public MPOSServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MPOSServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MPOSServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MPOSServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string _SPAJToCore(string in0, HtmlGeneratorServices.SinosoftWS.ArrayOfBase64Binary in1, HtmlGeneratorServices.SinosoftWS.ArrayOfBase64Binary in2, HtmlGeneratorServices.SinosoftWS.ArrayOfBase64Binary in3, HtmlGeneratorServices.SinosoftWS.ArrayOfBase64Binary in4) {
            return base.Channel._SPAJToCore(in0, in1, in2, in3, in4);
        }
    }
}
